### ISSUE TITLE
services script removes all containers and volumes

### ISSUE THREAD

**Issue by rivaldi8** [FIWARE/tutorials.Subscriptions#10]
`services` script calls [stoppingContainers](https://github.com/FIWARE/tutorials.Subscriptions/blob/NGSI-LD/services#L146) function which removes **all** containers and volumes in the machine where it's run, not only the ones from the tutorial.

**Comment by jason-fox** [comment]
`labels` have been added to the docker-compose file identifying the tutorial components.

The `stoppingContainers` function is in place to ensure the tutorial starts up  from a clean slate - it now reduces to: 

```bash
docker ps --filter "label=org.fiware=tutorial" -aq)
docker volume ls -qf dangling=true) 
docker network ls  --filter "label=org.fiware=tutorial" -q) 
```

Volumes is still removing dangling volumes, but networks and container are cleaning up nicely. If you still find the volumes command too aggressive, please update your local copy and comment out the lines [here](https://github.com/FIWARE/tutorials.Subscriptions/blob/master/services#L43-L47)
