### ISSUE TITLE
Cannot delete subscriptions 

### ISSUE THREAD

**Issue by hybuild-project** [FIWARE/tutorials.Subscriptions#13]
Hi, following the tutorial it is impossible to delete a subscription, because Orion replies:

{"error":"BadRequest","description":"Orion accepts no payload for GET/DELETE requests. HTTP header Content-Type is thus
forbidden"}

This should be an error because it happens also without any header set, also using the correspondent collection in Postman kindly provided here. Thanks.

**Comment by jason-fox** [comment]
Where are you looking?  Was it the NGSI-LD Postman collection? The raw body is unnecessary and has been removed a61242f. The text of the tutorials is already correct:

-  This text shows how to [delete an NGSI-v2 subscription](https://github.com/FIWARE/tutorials.Subscriptions#delete-a-subscription)
-  This text shows how to [delete an NGSI-LD subscription](https://github.com/FIWARE/tutorials.Subscriptions/blob/NGSI-LD/README.md#delete-a-subscription)
