### ISSUE TITLE
Subscription registration error

### ISSUE THREAD

**Issue by baston888** [FIWARE/tutorials.Subscriptions#14]
Dear developers, an attempt to execute the request given in README.md
![image](https://github.com/FIWARE/tutorials.Subscriptions/assets/72969990/f85d9e15-655b-4814-9b91-57586e78368e)
 leads to the following error 
![image](https://github.com/FIWARE/tutorials.Subscriptions/assets/72969990/72cad105-8f90-473a-9eca-1eaa483c2e44)

**Comment by jason-fox** [comment]
The controlledAsset now needs to be within quotes `"` - the parsing has tightened.
