### ISSUE TITLE
Orion-ld crashes when clicking the add button

### ISSUE THREAD

**Issue by baston888** [FIWARE/tutorials.Subscriptions#15]
Dear colleagues, pressing the add button in this application crashes orion-ld
![image](https://github.com/FIWARE/tutorials.Subscriptions/assets/72969990/7a82ff67-e7b5-4398-8937-391e319ae42b)
![image](https://github.com/FIWARE/tutorials.Subscriptions/assets/72969990/24aa6978-f9f8-4599-96a6-b9f7130dd6e8)

**Comment by jason-fox** [comment]
Reproducible with the following cURL:

```console
curl -L -X PATCH 'http://localhost:1026/ngsi-ld/v1/entities/urn:ngsi-ld:Device:filling001/attrs/remove' \
-H 'NGSILD-Tenant: openiot' \
-H 'Content-Type: application/json' \
-H 'Link: <http://context/ngsi-context.jsonld>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"' \
-d '{ 

		"type": "Property", 
		"value": " " 

}'
```

Is is most likely an Orion-LD 1.2.1 error.

**Comment by baston888** [comment]
This is last that is present in log of orion-ld after it crash
![image](https://github.com/FIWARE/tutorials.Subscriptions/assets/72969990/a2733a32-4a4f-4727-87a3-2d63be2cb886)
Therefore, the application made a request which resulted in a crash.
![image](https://github.com/FIWARE/tutorials.Subscriptions/assets/72969990/47b9e7c9-3a97-4fd8-a4bf-2a2847f3511a)
A check in mongo showed that the entity to which the request was addressed does not exist.
The reason for this lies in this error
![image](https://github.com/FIWARE/tutorials.Subscriptions/assets/72969990/8d37a3c1-a52d-468e-a61b-aa7aed92624f)

**Comment by baston888** [comment]
This issue is solved with last commit.
